# This is the global application.yml for the microservices
# Default port configuration for all microservices (Should not use it)
server:
 port: 8080

eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761