# This is the global application.yml for the microservices
# Default port configuration for all microservices (Should not use it)
server:
 port: 8080

# Eureka Server default zone configuration for all microservices
eureka:
 client:
   serviceUrl:
     defaultZone: http://CONFIGURATION-SERVER