spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rogeriotakashi/Microservices-SAGA-Patterns-Configuration.git
server:
 port: 8080
 
 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/