server:
  port: 10002

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: a
    password: a
  h2:
    console:
      enabled: true
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
 cloud:
  config:
   uri: http://localhost:8888