server:
  port: 10000

spring:
 application:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: a
    password: a
  h2:
    console:
      enabled: true
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka
     
     
spring:
  applcation:
    kafka:
    consumer:
      group-id: order
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    
    listener.missing-topics-fatal: false

app:
 topic:
  order-request: create.order.request.t
  order-response: create.order.response.t

